stableFlag = getMatrixStabilityMeasure(Counts{1,2},'slopeRange', 4e-3);
popResponse = getModulatedPopulationMeanResponse(Counts,...
    [wruIdx, signMod & stableFlag, potFlag]);
evolutionFigures = plotResponseEvolution(popResponse,...
    'windowDuration', diff(responseWindow),...
    'triggerTimes', trigTms,...
    'trialBin', 15, 'inMinutes', true,'error','SEM');

%% save (or overwrite) figures
modulationLabel = ["potentiated"; "depressed"];
arrayfun(@(x,y) saveFigure(x, fullfile(figureDir,...
    sprintf('Response evolution for %s stable clusters %s(%s)',...
    y, sprintf('%d ',chExp), structString)), 1, 1),...
    evolutionFigures, modulationLabel)
