aux = expMice.PolygonUnfoldAmplIndx([1,5],:,:,cons_mice);
med_AI_pbp = squeeze( median( aux, 2, "omitmissing" ) );
med_AI_all = median( med_AI_pbp, 3, "omitmissing" );
Nb = 8;
bodypart_names = ["Stim-whisker mean", "Stim-whisker fan arc", ...
"Nonstim-whisker mean", "Nonstim-whisker fan arc", "Interwhisk arc", ...
"Symmetry", "Nose", "Roller speed"];

radAxis = (0:Nb-1)*(2*pi/Nb);
z_axis = exp(1i*radAxis(:));

iqr_AI = quantile( med_AI_pbp, [1,3]/4, 3 );
iqr_coords = iqr_AI .* transp( z_axis );
poly_coords = med_AI_all .* transp( z_axis );

figure('Color', 'w'); hold on;
line( [-real(z_axis(1:4)), real(z_axis(1:4))]', ...
    [-imag(z_axis(1:4)), imag(z_axis(1:4))]', 'LineWidth', 0.1, ...
    'Color', 0.45*ones(1,3));
arrayfun(@(x) rectangle('Position', [repmat(-x,1,2),repmat(x*2,1,2)], ...
    'Curvature', [1,1], 'EdgeColor', 0.45*ones( 1, 3 ) ), 1:-0.25:0.25 );
arrayfun(@(c) patch( real( poly_coords(c,:) )', ...
    imag( poly_coords(c,:) )', clrMap(c,:), 'EdgeColor', 'none', ...
    'FaceAlpha', 0.8 ), 1:2 );

z_rot = exp( 1i*pi/32 ); 
% Dots by the polygon
arrayfun(@(c,z) line( real( poly_coords(c,:) * z)', ...
    imag( poly_coords(c,:) * z )', 'LineStyle', 'none', ...
    'Marker', '.', 'Color', clrMap(c,:), 'MarkerSize', 20 ), ...
    1:2, [z_rot, z_rot'] )
set( gca, 'Box', 'off', 'Color', 'none', "Visible", "off" );
% Lines for IQR
arrayfun(@(x,z) line( squeeze( real( iqr_coords(x,:,:) * z ) )', ...
    squeeze( imag( iqr_coords(x,:,:) * z ) )', 'LineWidth', 2, ...
    'Color', clrMap(x,:) ), 1:2, [z_rot, z_rot'] )
text( 0.25:0.25:1, zeros(1,4), string( ( 1:4 )'/4 ), ...
    "HorizontalAlignment", "left", "VerticalAlignment", "cap" )
title('Population Polygons for MC\rightarrowiRNs' )
legend( findobj( gca, 'Type', 'Patch' ), {'Laser OFF', 'Laser ON'}, ...
    "Location", "best", "Color", "none", "Box", "off" )
p = arrayfun(@(b) signrank( squeeze( med_AI_pbp(1,b,:) ), ...
    squeeze( med_AI_pbp(2,b,:) ) ), 1:8 );
arrayfun(@(v, y) text( real( 1.25*poly_coords(1,v) ), ...
    imag( 1.25*poly_coords(1,v) ), repmat( '\ast', 1, sum( p(v) < ...
    [0.05, 0.01, 0.001] ) ), "HorizontalAlignment", "center", ...
    "Rotation", y, "VerticalAlignment", "baseline"), 1:8, ...
    (180*angle( transp(z_axis) )/pi) - 90 );

arrayfun(@(v,b,y) text( real( z_axis(v) ), ...
    imag( z_axis(v) ), b, "HorizontalAlignment", "center", "Rotation", y, ...
    "VerticalAlignment", "baseline" ), 1:8, bodypart_names, ...
    (180*angle( transp(z_axis) )/pi) - 90 )