% crudeSNR
ind = find(VplSal.Laser_Control_15mW_LR & VplSal.Mech_Control_15mW_MR...
& VplSal.Laser_Control_15mW_Counts_Spont > VplSal.Laser_Control_15mW_Counts_Evoked...
& VplSal.Mech_Control_15mW_Counts_Spont < VplSal.Mech_Control_15mW_Counts_Evoked...
& VplSal.Mech_Control_15mW_vs_Mech_Laser_15mW_Evoked_Response);
SNRup15 = VplSal.id(ind);
ind = find(VplSal.Laser_Control_15mW_LR & VplSal.Mech_Control_15mW_MR...
& VplSal.Laser_Control_15mW_Counts_Spont < VplSal.Laser_Control_15mW_Counts_Evoked...
& VplSal.Mech_Control_15mW_Counts_Spont < VplSal.Mech_Control_15mW_Counts_Evoked...
& VplSal.Mech_Control_15mW_vs_Mech_Laser_15mW_Evoked_Response);
FRup15 = VplSal.id(ind);
ind = find(VplSal.Laser_Control_10mW_LR & VplSal.Mech_Control_10mW_MR...
& VplSal.Laser_Control_10mW_Counts_Spont > VplSal.Laser_Control_10mW_Counts_Evoked...
& VplSal.Mech_Control_10mW_Counts_Spont < VplSal.Mech_Control_10mW_Counts_Evoked...
& VplSal.Mech_Control_10mW_vs_Mech_Laser_10mW_Evoked_Response);
SNRup10 = VplSal.id(ind);
ind = find(VplSal.Laser_Control_10mW_LR & VplSal.Mech_Control_10mW_MR...
& VplSal.Laser_Control_10mW_Counts_Spont < VplSal.Laser_Control_10mW_Counts_Evoked...
& VplSal.Mech_Control_10mW_Counts_Spont < VplSal.Mech_Control_10mW_Counts_Evoked...
& VplSal.Mech_Control_10mW_vs_Mech_Laser_10mW_Evoked_Response);
FRup10 = VplSal.id(ind);
ind = find(VplSal.Laser_Control_5mW_LR & VplSal.Mech_Control_5mW_MR...
& VplSal.Laser_Control_5mW_Counts_Spont > VplSal.Laser_Control_5mW_Counts_Evoked...
& VplSal.Mech_Control_5mW_Counts_Spont < VplSal.Mech_Control_5mW_Counts_Evoked...
& VplSal.Mech_Control_5mW_vs_Mech_Laser_5mW_Evoked_Response);
SNRup5 = VplSal.id(ind);
ind = find(VplSal.Laser_Control_5mW_LR & VplSal.Mech_Control_5mW_MR...
& VplSal.Laser_Control_5mW_Counts_Spont < VplSal.Laser_Control_5mW_Counts_Evoked...
& VplSal.Mech_Control_5mW_Counts_Spont < VplSal.Mech_Control_5mW_Counts_Evoked...
& VplSal.Mech_Control_5mW_vs_Mech_Laser_5mW_Evoked_Response);
FRup5 = VplSal.id(ind);
ind = find(VplSal.Laser_Control_15mW_LR & VplSal.Mech_Control_15mW_MR...
& VplSal.Laser_Control_15mW_Counts_Spont < VplSal.Laser_Control_15mW_Counts_Evoked...
& VplSal.Mech_Control_15mW_Counts_Spont > VplSal.Mech_Control_15mW_Counts_Evoked...
& VplSal.Mech_Control_15mW_vs_Mech_Laser_15mW_Evoked_Response);
SNRdwn15 = VplSal.id(ind);
ind = find(VplSal.Laser_Control_15mW_LR & VplSal.Mech_Control_15mW_MR...
& VplSal.Laser_Control_15mW_Counts_Spont > VplSal.Laser_Control_15mW_Counts_Evoked...
& VplSal.Mech_Control_15mW_Counts_Spont > VplSal.Mech_Control_15mW_Counts_Evoked...
& VplSal.Mech_Control_15mW_vs_Mech_Laser_15mW_Evoked_Response);
FRdwn15 = VplSal.id(ind);
ind = find(VplSal.Laser_Control_10mW_LR & VplSal.Mech_Control_10mW_MR...
& VplSal.Laser_Control_10mW_Counts_Spont < VplSal.Laser_Control_10mW_Counts_Evoked...
& VplSal.Mech_Control_10mW_Counts_Spont > VplSal.Mech_Control_10mW_Counts_Evoked...
& VplSal.Mech_Control_10mW_vs_Mech_Laser_10mW_Evoked_Response);
SNRdwn10 = VplSal.id(ind);
ind = find(VplSal.Laser_Control_10mW_LR & VplSal.Mech_Control_10mW_MR...
& VplSal.Laser_Control_10mW_Counts_Spont > VplSal.Laser_Control_10mW_Counts_Evoked...
& VplSal.Mech_Control_10mW_Counts_Spont > VplSal.Mech_Control_10mW_Counts_Evoked...
& VplSal.Mech_Control_10mW_vs_Mech_Laser_10mW_Evoked_Response);
FRdwn10 = VplSal.id(ind);
ind = find(VplSal.Laser_Control_5mW_LR & VplSal.Mech_Control_5mW_MR...
& VplSal.Laser_Control_5mW_Counts_Spont < VplSal.Laser_Control_5mW_Counts_Evoked...
& VplSal.Mech_Control_5mW_Counts_Spont > VplSal.Mech_Control_5mW_Counts_Evoked...
& VplSal.Mech_Control_5mW_vs_Mech_Laser_5mW_Evoked_Response);
SNRdwn5 = VplSal.id(ind);
ind = find(VplSal.Laser_Control_5mW_LR & VplSal.Mech_Control_5mW_MR...
& VplSal.Laser_Control_5mW_Counts_Spont > VplSal.Laser_Control_5mW_Counts_Evoked...
& VplSal.Mech_Control_5mW_Counts_Spont > VplSal.Mech_Control_5mW_Counts_Evoked...
& VplSal.Mech_Control_5mW_vs_Mech_Laser_5mW_Evoked_Response);
FRdwn5 = VplSal.id(ind);
