function RateMap = plotRate(rates, ID, binSize, nUnits, numSamples, fs)

binSamples = fs*binSize;
nBins = round(numSamples/binSamples);
xaxisSec = [0:nBins]'*binSize;
yaxisClNo = [1:nUnits];

RateMap = figure('Color', 'White');
imagesc(xaxisSec, yaxisClNo, rates');
yticks(1:1:nUnits);
yticklabels(ID);
xlabel('Time (s)');
ylabel('Units');
txt = {['Bin Size = ', num2str(binSize) 's']};
text(8328,-2.7,1.4e-14, txt);
%Use fire colormap
colormap(fire);
colorbar;
%use caxis command to hardcode colormap so that we can more easily compare
caxis([0 50]);
ax = gca;
ax.FontSize = 30;
configureFigureToPDF(figure(RateMap));
% saveas(figure(RateMap), expt, 'emf');
% save(fullfile(dataDir, [expt]), 'rate', 'RateMap', '-v7.3');
end


%across conditions-- try it out with autogenerated values to get a sense of
%the appropriate scaling

%Add labels!

%RAM Can you programmatically save the figure file?
% savefig('RateMap.fig'); print('RateMap.pdf','-dpdf'); print('RateMap.emf','-dmeta');
%RAM Are you always using 50 ms or 500 ms for binsizes? Asnw: No, 1s bin size for
% these files
%RAM Add binsize to title or somewhere on plot
%RAM Wrap everything in a function as below and save in new .m file

%RAM programatically save results to a new data file using save command at
% command line